from __future__ import annotations

TOPIC_DEFINITIONS: dict[str, str] = {
    "accessibility": "making sites usable with assistive technology: ARIA, contrast, keyboard use",
    "algorithms": "designing and analysing algorithms: sorting, searching, recursion, complexity",
    "apis": "calling or building HTTP APIs: REST, JSON, authentication, rate limits",
    "aws": "Amazon Web Services products and certifications",
    "backend": "server-side application development: services, routing, persistence",
    "career-skills": "job search, interviews, portfolios, workplace communication",
    "cloud-computing": "cloud concepts and platforms: compute, storage, pricing, shared responsibility",
    "cryptography": "encryption, hashing, signatures, key management",
    "cybersecurity": "protecting systems and data: threats, vulnerabilities, controls, security operations",
    "data-analysis": "cleaning, transforming and interpreting data to answer questions",
    "data-science": "the end-to-end practice of extracting insight and predictions from data",
    "data-structures": "arrays, lists, maps, trees, graphs and how to choose between them",
    "data-visualization": "charts and plots that communicate data",
    "databases": "storing and querying data: relational and non-relational systems, schema design",
    "deep-learning": "neural networks with many layers: CNNs, transformers, training at scale",
    "devops": "build, release and operations practice: CI/CD, infrastructure as code, monitoring",
    "docker": "containers and images",
    "excel": "spreadsheets: formulas, pivot tables, charts",
    "frontend-frameworks": "component frameworks for user interfaces and their ecosystems",
    "generative-ai": "building with or understanding generative models and LLM applications",
    "git": "version control: commits, branches, merges, pull requests",
    "html-css": "page structure with HTML and styling with CSS",
    "incident-response": "detecting, triaging and recovering from security or operational incidents",
    "java": "the Java language and its ecosystem",
    "javascript": "the JavaScript language: syntax, closures, async, the DOM, modern ES features",
    "kubernetes": "container orchestration",
    "linux": "the Linux command line and operating system administration",
    "machine-learning": "training models from data: regression, classification, clustering, evaluation",
    "mobile-development": "building iOS or Android apps",
    "networking": "network protocols, addressing, routing, network security",
    "nlp": "natural language processing: text classification, embeddings, language models",
    "nodejs": "server-side JavaScript with Node.js",
    "object-oriented-programming": "classes, objects, inheritance, encapsulation, design patterns",
    "project-management": "planning, scheduling, delivery and team coordination",
    "prompt-engineering": "writing and evaluating prompts for language models",
    "python": "the Python language: syntax, standard library, packaging, idioms",
    "react": "the React library: components, hooks, state, rendering",
    "responsive-design": "layouts that adapt to screen size: flexbox, grid, media queries",
    "risk-management": "identifying, scoring and treating risks to a system or organisation",
    "sql": "the SQL query language: select, joins, aggregation, window functions",
    "statistics": "probability, distributions, hypothesis testing, inference",
    "testing": "unit, integration and end-to-end testing; test-driven development",
    "typescript": "typed JavaScript with TypeScript",
    "ux-design": "user research, interaction design, prototyping, usability",
    "web-development": "building websites and web applications end to end",
}

TOPIC_VOCABULARY: tuple[str, ...] = tuple(sorted(TOPIC_DEFINITIONS))
